apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: proxmox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "endpoint": "{{ .endpoint }}",
            "api_token": "{{ .apiToken }}",
            "insecure": "true"
          }

  data:
    - secretKey: endpoint
      remoteRef:
        key: proxmox/url

    - secretKey: apiToken
      remoteRef:
        key: proxmox/password
