apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/e-a-s-t/crossplane.git
    targetRevision: main
    path: providers

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
